### PR TITLE
feat(api-linter) fix api linter errors

### PR DESCRIPTION
**Pull request by toumorokoshi**

### CODE REVIEW

**Comment by toumorokoshi** [comment]
for posterity: remaining linter errors:

```
/home/yusuke.tsutsumi/go/bin/api-linter
- file_path: example/bookstore/bookstore.proto
  problems:
  - message: 'Unexpected field: Update RPCs must only contain fields explicitly described
      in AEPs, not "path".'
    location:
      start_position:
        line_number: 107
        column_number: 3
      end_position:
        line_number: 110
        column_number: 4
      path: example/bookstore/bookstore.proto
    rule_id: core::0134::request-unknown-fields
    rule_doc_uri: https://linter.aip.dev/134/request-unknown-fields
  - message: 'Proto package and directory structure mismatch: The proto package must
      match the proto directory structure.'
    location:
      start_position:
        line_number: 3
        column_number: 1
      end_position:
        line_number: 3
        column_number: 18
      path: example/bookstore/bookstore.proto
    rule_id: core::0191::proto-package
    rule_doc_uri: https://linter.aip.dev/191/proto-package
  - message: List responses should only contain fields explicitly described in AEPs.
    location:
      start_position:
        line_number: 146
        column_number: 3
      end_position:
        line_number: 146
        column_number: 21
      path: example/bookstore/bookstore.proto
    rule_id: core::0132::response-unknown-fields
    rule_doc_uri: https://linter.aip.dev/132/response-unknown-fields
  - message: Create RPCs must only contain fields explicitly described in AEPs, not
      "path".
    location:
      start_position:
        line_number: 86
        column_number: 3
      end_position:
        line_number: 89
        column_number: 4
      path: example/bookstore/bookstore.proto
    rule_id: core::0133::request-unknown-fields
    rule_doc_uri: https://linter.aip.dev/133/request-unknown-fields
  - message: The method signature for Update methods should be "book,update_mask".
    suggestion: option (google.api.method_signature) = "book,update_mask";
    location:
      start_position:
        line_number: 39
        column_number: 5
      end_position:
        line_number: 39
        column_number: 66
      path: example/bookstore/bookstore.proto
    rule_id: core::0134::method-signature
    rule_doc_uri: https://linter.aip.dev/134/method-signature
  - message: Custom methods should use the HTTP POST or GET method.
    location:
      start_position:
        line_number: 58
        column_number: 5
      end_position:
        line_number: 58
        column_number: 72
      path: example/bookstore/bookstore.proto
    rule_id: core::0136::http-method
    rule_doc_uri: https://linter.aip.dev/136/http-method
  - message: The first field of paginated RPCs must have a protobuf ID of 1.
    location:
      start_position:
        line_number: 146
        column_number: 3
      end_position:
        line_number: 146
        column_number: 21
      path: example/bookstore/bookstore.proto
    rule_id: core::0158::response-repeated-first-field
    rule_doc_uri: https://linter.aip.dev/158/response-repeated-first-field
  - message: List RPCs should only contain fields explicitly described in AEPs.
    location:
      start_position:
        line_number: 140
        column_number: 3
      end_position:
        line_number: 140
        column_number: 30
      path: example/bookstore/bookstore.proto
    rule_id: core::0132::request-unknown-fields
    rule_doc_uri: https://linter.aip.dev/132/request-unknown-fields
  - message: Update RPCs must only require fields explicitly described in AEPs, not
      "path".
    location:
      start_position:
        line_number: 107
        column_number: 3
      end_position:
        line_number: 110
        column_number: 4
      path: example/bookstore/bookstore.proto
    rule_id: core::0134::request-required-fields
    rule_doc_uri: https://linter.aip.dev/134/request-required-fields
  - message: The method signature for Create methods should be "parent,book".
    suggestion: option (google.api.method_signature) = "parent,book";
    location:
      start_position:
        line_number: 25
        column_number: 5
      end_position:
        line_number: 25
        column_number: 61
      path: example/bookstore/bookstore.proto
    rule_id: core::0133::method-signature
    rule_doc_uri: https://linter.aip.dev/133/method-signature
  - message: Create RPCs must only require fields explicitly described in AEPs, not
      "path".
    location:
      start_position:
        line_number: 86
        column_number: 3
      end_position:
        line_number: 89
        column_number: 4
      path: example/bookstore/bookstore.proto
    rule_id: core::0133::request-required-fields
    rule_doc_uri: https://linter.aip.dev/133/request-required-fields


```

**Comment by toumorokoshi** [comment]
Here's two that might be better off fixed in the linter:

```
- message: The first field of paginated RPCs must have a protobuf ID of 1.
    location:
      start_position:
        line_number: 146
        column_number: 3
      end_position:
        line_number: 146
        column_number: 21
      path: example/bookstore/bookstore.proto
    rule_id: core::0158::response-repeated-first-field
    rule_doc_uri: https://linter.aip.dev/158/response-repeated-first-field
# doesn't like int32 max_page_size = 10017 for some reason
- message: List responses should only contain fields explicitly described in AEPs.
    location:
      start_position:
        line_number: 146
        column_number: 3
      end_position:
        line_number: 146
        column_number: 21
      path: example/bookstore/bookstore.proto
    rule_id: core::0132::response-unknown-fields
    rule_doc_uri: https://linter.aip.dev/132/response-unknown-fields
```

1 is because the generated proto has a field number in the 10k+ range, which helps avoid collisions with existing fields: https://github.com/aep-dev/aepc/blob/85396a2a178bda34bec944b45514393cc259f131/example/bookstore/bookstore.proto#L140. 

I could make the field number for this 1 in the generator - but I'm kind of wondering how valuable it is to be prescriptive with field numbers? might make it hard for someone to adapt to AEPs if field numbers are already used? 

for 2 I'm not really sure: [the field looks to be corrrect for max_page_size](https://github.com/aep-dev/aepc/blob/85396a2a178bda34bec944b45514393cc259f131/example/bookstore/bookstore.proto#L134). 

The other linting errors above are due to:

- a change I'd like to push to have `update` also use a field name `path` to identify the resource, so we can get rid of the `identifier` field behavior.
- because I've added an apply method - I'll send an AEP on that at some point.
- still figuring out the story for proto paths - I think I need to update aepc and the example to generate the correct structure. 

CC @rambleraptor for thoughts.

**Comment by rambleraptor** [comment]
We changed the guidance on AEP-158 so that the first field does not need to be the pagination results. I've created [this PR](https://github.com/aep-dev/api-linter/pull/84) to look for a repeated field, instead of forcing that field to be the first by order/ID.

**Comment by rambleraptor** [comment]
It looks like `max_page_size` isn't an allowed field. [PR to fix](https://github.com/aep-dev/api-linter/pull/85)

**Comment by toumorokoshi** [comment]
Awesome, thank you! that just leaves the a few more issues, with one fixed by https://github.com/aep-dev/aep.dev/pull/210.

The last one is the existence of an apply method - which we might be able to remove once the openapi terraform generator can use PATCH with json-merge-patch instead of PUT.

**Pull request merged**
